# Configurações Diretas (Troque apenas se os dados mudaram)
spring.datasource.url=jdbc:postgresql://shuttle.proxy.rlwy.net:33135/railway
spring.datasource.username=postgres
spring.datasource.password=XPVTdcXVmRttyHotfZVZfVHkRVylKVMc
spring.datasource.driver-class-name=org.postgresql.Driver

# Forçar o Hibernate a usar PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Servidor (O Railway precisa disso)
server.port=${PORT:9090}