spring.datasource.url=jdbc:postgresql://shuttle.proxy.rlwy.net:33135/railway
spring.datasource.username=postgres
spring.datasource.password=XPVTdcXVmRttyHotfZVZfVHkRVylKVMc
spring.datasource.driver-class-name=org.postgresql.Driver

# FORÇAR CRIAÇÃO DE TABELAS
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# PORTA DO RAILWAY
server.port=${PORT:9090}